version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    ports:
      - 9090:9090
    restart: always
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-app
    ports:
      - 8080:8080
    restart: always